### PR TITLE
Upgrade to Terraform 0.12

### PR DESCRIPTION
**Pull request by eana**
This PR:

* Refactors the code to work with terraform 0.12.
* It fixes broken kubernetes-dashboard and calico addons.
* It removes the duplicate user, context and cluster from the kubectl config.

### CODE REVIEW

**Comment by eana** [comment]
@vlesierse Is there anything I can do to get this moved forward? Thanks!

**Comment by vlesierse** [comment]
Might be a good moment to make a 1.0 release?

**Comment by eana** [comment]
What would you say about having a similar approach as [terraform-aws-vpc
](https://github.com/terraform-aws-modules/terraform-aws-vpc)

* Terraform 0.12. Pin module version to `~> v2.0`.
* Terraform 0.11. Pin module version to `~> v1.0`.

**Comment by eana** [comment]
Thanks for reviewing the changes. What do you think about my suggestion in regards to the module version?

**Comment by vlesierse** [comment]
I agree, we can change the README to explain the versioning. Will make the change and tag the release after this merge.

**Comment by eana** [comment]
Thanks for reviewing the changes. What do you think about the release suggestion?

**Pull request merged**
